[project]
name = "zennit-crp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    'zennit<=0.4.6',
    'torch>=1.7.0, <2.0.0',
    'numpy<=1.23.5',
    'tqdm',
    'matplotlib',
    "ipykernel>=6.29.5",
    "scipy>=1.15.2",
]
